<?php

/**
 * BaseReplacementTask
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Vehicle $Vehicle
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReplacementTask extends Task
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Vehicle', array(
             'local' => 'new_vehicle_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}