<?php

/**
 * PluginAccidentTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAccidentTaskTable extends TaskTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAccidentTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAccidentTask');
    }
}