<?php

/**
 * BaseParticipantContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $participant_id
 * @property string $street_number
 * @property string $house_number
 * @property string $pobox
 * @property string $mobile_number
 * @property string $phone_number
 * @property string $fax
 * @property string $email
 * @property string $website
 * @property Participant $Participant
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParticipantContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('participant_contact');
        $this->hasColumn('participant_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('street_number', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('house_number', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('pobox', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('mobile_number', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone_number', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('fax', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('website', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Participant', array(
             'local' => 'participant_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}