<?php

/**
 * BaseParticipantType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property clob $description
 * @property Doctrine_Collection $participantTypeParticipants
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParticipantType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('participant_type');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Participant as participantTypeParticipants', array(
             'local' => 'id',
             'foreign' => 'participant_type_id'));
    }
}