<?php

/**
 * PluginAssignmentOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAssignmentOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAssignmentOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAssignmentOrder');
    }
}