<?php

/**
 * PluginAssignmentTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAssignmentTaskTable extends TaskTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAssignmentTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAssignmentTask');
    }
}