<?php

/**
 * AssignedVehicle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AssignedVehicle extends PluginAssignedVehicle
{
	public function processDeparture()
	{
		$this->is_departed = true;
		$this->save();
	}
	
	public function processReturn()
	{
		$this->is_returned = false;
		$this->is_departed = false;
		$this->save();
	}
}
