<?php

/**
 * VehicleServiceTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VehicleServiceTypeTable extends PluginVehicleServiceTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object VehicleServiceTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VehicleServiceType');
    }
}