<?php

/**
 * VehicleFuelSettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VehicleFuelSettingTable extends PluginVehicleFuelSettingTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object VehicleFuelSettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VehicleFuelSetting');
    }
}