<?php

/**
 * VehicleChakupSettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VehicleChakupSettingTable extends PluginVehicleChakupSettingTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object VehicleChakupSettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VehicleChakupSetting');
    }
}