<?php

/**
 * VehicleTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VehicleTypeTable extends PluginVehicleTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object VehicleTypeTable
     */
	public static function getInstance()
	{
	  return Doctrine_Core::getTable('VehicleType');
	}
	
	public static function isNameDuplicated( $name )
   {
		return self::findWtithName ( $name );
	}
   
   public static function processCreate ($name, $description )
	{
		$is_duplicated = self::isNameDuplicated ( $name );
		
		try {
			
			if($is_duplicated)
				return false;
				
			if(is_null($name) || empty($name))
				return false;
				
			$_nw = new vehicleType();   
			$_nw->name = trim($name);   
			$_nw->alias = tirm(strtolower($name));
			$_nw->description = trim($description); 
			$_nw->save(); 
			
			return true;
			
		} catch ( Exception $e ) {
			
			return false; 
		}	 
		  
	}

	public static function processUpdate ($_id, $name, $description )
	{
		$q = Doctrine_Query::create( )
			->update('vehicleType ft')
			->set('ft.name', '?', trim($name))  
			->set('ft.description', '?', trim($description))  
			->where('ft.id = ?', $_id)
			->execute();	

		return ( $q > 0 );   
	}
   
   public static function processDelete ( $_id ) 
   {
		$q = Doctrine_Query::create( )
			->delete ('vehicleType ft')
			->where('ft.id=?', $_id)
			->execute ( );	
		return ( $q	> 0  );  
	}
	
	public static function processObject ( $_id ) 
	{
		$q = Doctrine_Query::create( )
							->select("ft.*, ft.name as vehicleTypeName")
							->from("vehicleType ft") 
							->where("ft.id=?", $_id)
							->fetchOne ( );
		return ( ! $q ? null : $q ); 
	}
	
	public static function findWtithName ( $name ) 
	{
		$q = Doctrine_Query::create( )
							->select("ft.*")
							->from("vehicleType ft") 
							->where("ft.name LIKE ?", trim($name))
							->fetchOne ( );
							
		return ( count($q) <= 0 ? null : $q); 
	}
    
	public static function processSelection ( $offset=0, $limit=100 ) 
	{
		$q = Doctrine_Query::create( )
							->select("ft.*, ft.name as vehicleTypeName")
							->from("vehicleType ft") 
							->offset($offset)
							->limit($limit)
							->execute ( );
		return ( count($q) <= 0 ? null : $q ); 
	}
	 
}
