<?php

/**
 * VehicleCheckupSettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VehicleCheckupSettingTable extends PluginVehicleCheckupSettingTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object VehicleCheckupSettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VehicleCheckupSetting');
    }
}