<?php

/**
 * VehicleChakupPeriodTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VehicleChakupPeriodTable extends PluginVehicleChakupPeriodTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object VehicleChakupPeriodTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VehicleChakupPeriod');
    }
}