<?php

/**
 * VehicleInsuranceSettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VehicleInsuranceSettingTable extends PluginVehicleInsuranceSettingTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object VehicleInsuranceSettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VehicleInsuranceSetting');
    }
}