<?php

/**
 * BaseServiceVehicleAccident
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $task_id
 * @property integer $vehicle_id
 * @property integer $accident_type_id
 * @property string $accident_place
 * @property datetime $accident_date
 * @property string $accident_time
 * @property Task $Task
 * @property Vehicle $Vehicle
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServiceVehicleAccident extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('service_vehicle_accident');
        $this->hasColumn('task_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('vehicle_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('accident_type_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('accident_place', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('accident_date', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('accident_time', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Task', array(
             'local' => 'task_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Vehicle', array(
             'local' => 'vehicle_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}