<?php

/**
 * BaseFleetServiceTask
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property ServiceType $ServiceType
 * @property Participant $Participant
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFleetServiceTask extends Task
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ServiceType', array(
             'local' => 'service_type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Participant', array(
             'local' => 'agreement_participant_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}