<?php

/**
 * BaseCategoryGroups
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $characterization_id
 * @property integer $category_id
 * @property boolean $pin_applies
 * @property boolean $is_sparepart
 * @property boolean $is_document
 * @property integer $grp
 * @property Category $Category
 * @property Doctrine_Collection $itemCategoryGroups
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryGroups extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_groups');
        $this->hasColumn('characterization_id', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('pin_applies', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_sparepart', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_document', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('grp', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Item as itemCategoryGroups', array(
             'local' => 'id',
             'foreign' => 'category_group_id'));
    }
}