<?php

/**
 * PluginServiceAccidentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginServiceAccidentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginServiceAccidentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginServiceAccident');
    }
}