<?php

/**
 * PluginServiceVehicleItemAcquiredTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginServiceVehicleItemAcquiredTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginServiceVehicleItemAcquiredTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginServiceVehicleItemAcquired');
    }
}