<?php

/**
 * PluginServiceVehicleAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginServiceVehicleAttachmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginServiceVehicleAttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginServiceVehicleAttachment');
    }
}