<?php

/**
 * PluginServiceTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginServiceTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginServiceTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginServiceType');
    }
}