<?php

/**
 * PluginServiceVehicleAccidentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginServiceVehicleAccidentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginServiceVehicleAccidentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginServiceVehicleAccident');
    }
}