<?php

/**
 * PluginFleetServiceTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFleetServiceTaskTable extends TaskTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginFleetServiceTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFleetServiceTask');
    }
}