<?php

/**
 * PluginMaintenanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMaintenanceTable extends TaskTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMaintenanceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMaintenance');
    }
}