<?php

/**
 * PluginMaintenanceTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMaintenanceTaskTable extends TaskTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMaintenanceTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMaintenanceTask');
    }
}