<?php

/**
 * PluginTaskAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTaskAttachmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTaskAttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTaskAttachment');
    }
}