<?php

/**
 * PluginTaskTransactionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTaskTransactionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTaskTransactionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTaskTransaction');
    }
}