<?php

/**
 * PluginTaskParticipantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTaskParticipantTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTaskParticipantTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTaskParticipant');
    }
}