<?php

/**
 * PluginTaskPassengersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTaskPassengersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTaskPassengersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTaskPassengers');
    }
}