<?php

/**
 * TimeMetricConversionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TimeMetricConversionTable extends PluginTimeMetricConversionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TimeMetricConversionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TimeMetricConversion');
    }
}