<?php

/**
 * UnitConversionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnitConversionTable extends PluginUnitConversionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnitConversionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UnitConversion');
    }
}