# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View
default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow
    #bootstrap/css/bootstrap.css,jquery-ui-1.8.21.custom.css,jquery.ui.accordion.css,
  stylesheets:    [ui-style.css, layout-default-latest.css,main.css,layout.css,jquery.treeview.css,/datatables/media/css/demo_table.css,login.css,redmond.calendars.picker.css,smoothness/jquery-ui-1.8.21.custom.css,css/redmond/jquery-ui-1.9.0.custom.css,styles.css,list.css, print: { media: print }]

# stylesheets:    [smoothness/jquery-ui-1.8.21.custom.css,layout-default-#latest.css,jquery.scrollpane.css,scroll.css,input_auto_complete_tag.css,main.css,layout.css,jquery.treeview.css,/datatables/media/css/#demo_table.css,styles.css,list.css,login.css,docs.css,admin.css,prettify.css,scroll.css,bootstrap.css,bootstrap.min.css, bootstrap-responsive.css]

#stylesheets:    [ styles.css, jquery.ui.dialog.css, jquery.ui.core.css,main.css, jquery-ui-1.8.16.custom.css]
#jquery-ui-1.8.16.custom.css, demo.css, main.css,/smoothness/jquery-ui-1.8.21.custom.css, jquery.ui.accordion.css]
  javascripts:    [tree/jquery.js,jquery-latest.js,jquery.tools.min.js, jquery.layout-latest.js,jquery-ui-1.8.21.custom.min.js,dialog.js,jquery.mousewheel.js,jquery.scrollpane.js,/datatables/media/js/jquery.dataTables.js,layout.js,accordion.js,scrollbar.js,tree/jquery.js,tree/jquery.cookie.js,tree/jquery.treeview.js,tree/demo.js,calendar/jquery.calendars.js,calendar/jquery.calendars.plus.js,calendar/jquery.calendars.picker.js,calendar/jquery.calendars.ethiopian-am.js,calendar/jquery.calendars.ethiopian.js,calendar/amharicdate.js,	redmond/js/jquery-1.8.2.js,redmond/js/jquery-ui-1.9.0.custom.js,checkbox.js, slider.js] 
#,datepicker.js,ajaxcall.js
#jquery.dataTables.js, ,
#builder.js,js/controls.js,js/dragdrop.js,js/effects.js,js/prototype.js,js/scriptaculous.js,js/slider.js,js/sound.js,js/unittest.js,
#javascripts:    [jquery-1.7.2.min.js, jquery-ui-1.8.21.custom.min.js,jquery.ui.all.js,main.js,layout.js,ajaxcall.js,jquery.layout.js]
#javascripts:    [jquery.ui.all.js, jqueryui/js/jquery-1.7.2.min.js, jqueryui/js/jquery-ui-1.8.21.custom.min.js]
#accordion.js,jquery.ui.core.js,jquery.ui.widget.js,jquery.ui.mouse.js,jquery.ui.button.js,jquery.ui.draggable.js,jquery.ui.position.js,jquery.ui.dialog.js,jquery.ui.resizable.js,jquery.effects.core.js,jquery.js,jquelayout.js]
  has_layout:     true
  layout:         layout
