<?php

/**
 * TaskAccidentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskAccidentTable extends PluginTaskAccidentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaskAccidentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaskAccident');
    }
}