<?php

/**
 * PluginCheckUpTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCheckUpTaskTable extends TaskTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCheckUpTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCheckUpTask');
    }
}