<?php

/**
 * PluginCheckUpSettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCheckUpSettingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCheckUpSettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCheckUpSetting');
    }
}