<?php

/**
 * ReplacementTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReplacementTaskTable extends PluginReplacementTaskTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReplacementTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReplacementTask');
    }
}