<?php

/**
 * AccidentTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AccidentTaskTable extends PluginAccidentTaskTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object AccidentTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AccidentTask');
    }
}