<?php

/**
 * BaseModulePermissionSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $module_name
 * @property clob $description
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseModulePermissionSetting extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('module_permission_setting');
        $this->hasColumn('module_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}