<?php

/**
 * BaseSystemLogFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $token_id
 * @property string $action_date
 * @property string $action_time
 * @property string $module_name
 * @property string $deleted_date
 * @property string $created_date
 * @property string $viewed_date
 * @property string $edited_date
 * @property integer $action_type_id
 * @property string $pc_ip_address
 * @property User $User
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSystemLogFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('system_log_file');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('token_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('action_date', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('action_time', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('module_name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('deleted_date', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('created_date', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('viewed_date', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('edited_date', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('action_type_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('pc_ip_address', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}