<?php

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $participant_id
 * @property string $username
 * @property string $password
 * @property string $token_id
 * @property integer $group_id
 * @property boolean $is_active
 * @property boolean $is_blocked
 * @property boolean $is_super_admin
 * @property boolean $status
 * @property integer $permission_mode
 * @property integer $ui_theme_color_setting
 * @property integer $ui_language_setting
 * @property UserGroup $UserGroup
 * @property Participant $Participant
 * @property Doctrine_Collection $userModulePermissions
 * @property Doctrine_Collection $userSystemLogFileActivities
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('participant_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('username', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('token_id', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('is_blocked', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('is_super_admin', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('permission_mode', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ui_theme_color_setting', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ui_language_setting', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UserGroup', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Participant', array(
             'local' => 'participant_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Permission as userModulePermissions', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('SystemLogFile as userSystemLogFileActivities', array(
             'local' => 'id',
             'foreign' => 'user_id'));
    }
}