<?php

/**
 * PluginSparepartTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSparepartTable extends ItemTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSparepartTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSparepart');
    }
}