<?php

/**
 * PluginVehicleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginVehicleTable extends ItemTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginVehicleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginVehicle');
    }
}