<?php

/**
 * PluginItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginItem');
    }
}