<?php

/**
 * PluginCategoryGroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCategoryGroupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCategoryGroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCategoryGroups');
    }
}