<?php

/**
 * CheckUpOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CheckUpOrderTable extends PluginCheckUpOrderTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CheckUpOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CheckUpOrder');
    }
}