<?php

/**
 * PluginVehicleChakupSettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginVehicleChakupSettingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginVehicleChakupSettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginVehicleChakupSetting');
    }
}