<?php

/**
 * PluginVehicleTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginVehicleTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginVehicleTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginVehicleType');
    }
}