<?php

/**
 * PluginVehicleFuelSettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginVehicleFuelSettingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginVehicleFuelSettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginVehicleFuelSetting');
    }
}