<?php

/**
 * PluginAssignedVehicleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAssignedVehicleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAssignedVehicleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAssignedVehicle');
    }
}