<?php

/**
 * PluginVehicleCheckupSettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginVehicleCheckupSettingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginVehicleCheckupSettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginVehicleCheckupSetting');
    }
}