<?php

/**
 * PluginTemporaryAssignmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTemporaryAssignmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTemporaryAssignmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTemporaryAssignment');
    }
}