<?php

/**
 * PluginVehicleInsuranceSettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginVehicleInsuranceSettingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginVehicleInsuranceSettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginVehicleInsuranceSetting');
    }
}