<?php

/**
 * ItemAcquiredAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ItemAcquiredAttachmentTable extends PluginItemAcquiredAttachmentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ItemAcquiredAttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ItemAcquiredAttachment');
    }
}