<?php

/**
 * TaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskTable extends PluginTaskTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Task');
    }
}