<?php

/**
 * TaskAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskAttachmentTable extends PluginTaskAttachmentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaskAttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaskAttachment');
    }
}