<?php

/**
 * BaseCheckUpSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $check_up_name
 * @property boolean $pass_value
 * @property boolean $fail_value
 * @property boolean $na_value
 * @property Doctrine_Collection $checkupSettingTaskOrders
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCheckUpSetting extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('check_up_setting');
        $this->hasColumn('check_up_name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('pass_value', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('fail_value', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('na_value', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CheckUpOrder as checkupSettingTaskOrders', array(
             'local' => 'id',
             'foreign' => 'checkup_setting_id'));
    }
}