<?php

/**
 * PluginTransferTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTransferTaskTable extends TaskTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTransferTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTransferTask');
    }
}