<?php

/**
 * BaseTaskOrder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $task_id
 * @property integer $pb_id
 * @property integer $acquired_for
 * @property integer $budget_source
 * @property integer $category_id
 * @property integer $category_group_id
 * @property integer $clss
 * @property integer $unit_id
 * @property float $planned_quantity
 * @property float $actual_quantity
 * @property float $remaining
 * @property float $unit_price
 * @property boolean $vat
 * @property integer $currency_id
 * @property float $amount
 * @property integer $effective_date
 * @property integer $status
 * @property string $description
 * @property float $sealed_count
 * @property float $used_count
 * @property float $concrete_count
 * @property float $nasty_count
 * @property float $disposed_count
 * @property Task $Task
 * @property Category $Category
 * @property Unit $Unit
 * @property Currency $Currency
 * @property Participant $Participant
 * @property Doctrine_Collection $itemTaskOrders
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaskOrder extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('task_order');
        $this->hasColumn('task_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('pb_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('acquired_for', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('budget_source', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('category_group_id', 'integer', null, array(
             'type' => 'integer',
             'default' => 2,
             ));
        $this->hasColumn('clss', 'integer', null, array(
             'type' => 'integer',
             'default' => 5,
             ));
        $this->hasColumn('unit_id', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
        $this->hasColumn('planned_quantity', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('actual_quantity', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('remaining', 'float', null, array(
             'type' => 'float',
             'default' => 0,
             ));
        $this->hasColumn('unit_price', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('vat', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('currency_id', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
        $this->hasColumn('amount', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('effective_date', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('sealed_count', 'float', null, array(
             'type' => 'float',
             'default' => 0,
             ));
        $this->hasColumn('used_count', 'float', null, array(
             'type' => 'float',
             'default' => 0,
             ));
        $this->hasColumn('concrete_count', 'float', null, array(
             'type' => 'float',
             'default' => 0,
             ));
        $this->hasColumn('nasty_count', 'float', null, array(
             'type' => 'float',
             'default' => 0,
             ));
        $this->hasColumn('disposed_count', 'float', null, array(
             'type' => 'float',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Task', array(
             'local' => 'task_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Unit', array(
             'local' => 'unit_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Currency', array(
             'local' => 'currency_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Participant', array(
             'local' => 'acquired_for',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Item as itemTaskOrders', array(
             'local' => 'id',
             'foreign' => 'task_order_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}