<?php

/**
 * PluginTaskIncidentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTaskIncidentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTaskIncidentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTaskIncident');
    }
}