<?php

/**
 * ModulePermissionSettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModulePermissionSettingTable extends PluginModulePermissionSettingTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModulePermissionSettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModulePermissionSetting');
    }
}