<?php

/**
 * SystemLogFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SystemLogFileTable extends PluginSystemLogFileTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SystemLogFileTable
     */
     
    public static $CREATE = 1;
    public static $UPDATE = 2;
    public static $READ = 3;
    public static $DELETE = 4;
    public static $LOGIN = 5;
    public static $LOGOUT = 6;
    
    public static $ALL_ACTIONS = array (1 => 'CREATE', 2 => 'UPDATE', 3 => 'READ', 4 => 'DELETE', 5 => 'LOGIN', 6 => 'LOGOUT');
    
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SystemLogFile');
    }
    
    public static function findActionID ( $value ) {
        try {
            foreach( self::$ALL_ACTIONS as $key=> $action ){
                    if( strcmp($action, $value) == 0 )
                        return $key; 
            }
            return null; 
            //throw new OutOfBoundException(" '$value'ዘይፍቀድ. "); 	
        } catch ( Exception $e ) {
            return null; 
        }
	}
	
	public static function findActionValue ($_id ){
        try {
            foreach( self::$ALL_ACTIONS as $key=> $action ){
                    if( $key == $_id )
                        return $action; 
            }
            return null; 
        //throw new OutOfBoundException(" '$id' ካብ ዝተፈቐደ ወፃኢ. ");             
        } catch ( Exception $e ) {
            return null; 
        }
	}
	
   public static function processCreate($user_id, $module_name, $action_id, $action_time, $action_date, $created_data,  $edited_data, $deleted_data, $viewed_data, $pc_ip_address)
	{
		$token = trim($action_date).trim($pc_ip_address).rand('11111', '99999');
		$_nw = new SystemLogFile();  
		$_nw->token_id = MD5($token);
		$_nw->user_id = $user_id;
		$_nw->module_name = trim($module_name);
		$_nw->action_type_id = $action_id;
		$_nw->action_time = $action_time;
		$_nw->action_date = $action_date;
		$_nw->created_data = $created_data;
		$_nw->deleted_data = $deleted_data;
		$_nw->edited_data = $edited_data;
		$_nw->viewed_data = $viewed_data;
		$_nw->pc_ip_address = $pc_ip_address; 
		$_nw->save(); 
		
		return true; 
	 
	}
	
	public static function processSelection($offset=0, $limit=20) 
	{
		$q= Doctrine_Query::create()
			->select("log.*, usr.username as userName, grp.name as groupName, log.action_date as accessDate, log.action_time as accessTime, log.action_type_id as accessAction, log.created_data as createdData")
			->from("SystemLogFile log") 
			->innerJoin("log.User usr on usr.id = log.user_id")
			->innerJoin("usr.UserGroup grp on grp.id = usr.group_id")
			->offset($offset)
			->limit($limit)
			->orderBy("log.id DESC")
			->execute( ); 

		return ( count ( $q ) <= 0 ? null : $q ); 
	}

}
