<?php

/**
 * PluginCompanyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCompanyTable extends ParticipantTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCompanyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCompany');
    }
}