<?php

/**
 * PluginCampusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCampusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCampusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCampus');
    }
}