<?php

/**
 * PluginOfficeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOfficeTable extends ParticipantTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOfficeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOffice');
    }
}