<?php

/**
 * PluginCollegeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCollegeTable extends ParticipantTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCollegeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCollege');
    }
}