<?php

/**
 * PluginEmployeeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEmployeeTable extends ParticipantTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEmployeeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEmployee');
    }
}