<?php

/**
 * PluginParticipantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginParticipantTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginParticipantTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginParticipant');
    }
}