<?php

/**
 * PluginSectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSectionTable extends ParticipantTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSection');
    }
}