<?php

/**
 * PluginParticipantTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginParticipantTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginParticipantTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginParticipantType');
    }
}