<?php

/**
 * TaskPassengersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskPassengersTable extends PluginTaskPassengersTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaskPassengersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaskPassengers');
    }
}