<?php

/**
 * TaskTransactionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskTransactionTable extends PluginTaskTransactionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaskTransactionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaskTransaction');
    }
}