<?php

/**
 * BaseTaskExpenseRequired
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $task_id
 * @property integer $expense_type_id
 * @property string $expense_date
 * @property integer $reference_no
 * @property integer $unit_id
 * @property integer $currency_id
 * @property float $quantity
 * @property float $unit_price
 * @property float $total_price
 * @property Task $Task
 * @property Unit $Unit
 * @property Currency $Currency
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaskExpenseRequired extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('task_expense_required');
        $this->hasColumn('task_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('expense_type_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('expense_date', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('reference_no', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('unit_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('currency_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('quantity', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('unit_price', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('total_price', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Task', array(
             'local' => 'task_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Unit', array(
             'local' => 'unit_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Currency', array(
             'local' => 'currency_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}