<?php

/**
 * BaseUnitConversion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $from_unit_id
 * @property integer $to_unit_id
 * @property double $rate
 * @property Unit $Unit
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUnitConversion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('unit_conversion');
        $this->hasColumn('from_unit_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('to_unit_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rate', 'double', null, array(
             'type' => 'double',
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Unit', array(
             'local' => 'from_unit_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}