<?php

/**
 * BaseCurrencyExchange
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $from_currency_id
 * @property integer $to_currency_id
 * @property float $rate
 * @property Currency $Currency
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCurrencyExchange extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('currency_exchange');
        $this->hasColumn('from_currency_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('to_currency_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rate', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Currency', array(
             'local' => 'to_currency_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}