<?php

/**
 * BaseTimeMetricConversion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $from_timemetric_id
 * @property integer $to_timemetric_id
 * @property float $rate
 * @property TimeMetric $TimeMetric
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTimeMetricConversion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('time_metric_conversion');
        $this->hasColumn('from_timemetric_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('to_timemetric_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('rate', 'float', null, array(
             'type' => 'float',
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TimeMetric', array(
             'local' => 'to_timemetric_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}