<?php

/**
 * PluginModulePermissionSettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginModulePermissionSettingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginModulePermissionSettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginModulePermissionSetting');
    }
}