<?php

/**
 * PluginSystemLogFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSystemLogFileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSystemLogFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSystemLogFile');
    }
}