<?php

/**
 * PluginUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUser');
    }
}