<?php

/**
 * BaseTaskTransaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $task_id
 * @property integer $token_id
 * @property clob $cost_description
 * @property string $transaction_date
 * @property float $cost_credited
 * @property float $cost_debited
 * @property float $cost_balance
 * @property Task $Task
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaskTransaction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('task_transaction');
        $this->hasColumn('task_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('token_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('cost_description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('transaction_date', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('cost_credited', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('cost_debited', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('cost_balance', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Task', array(
             'local' => 'task_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}