<?php

/**
 * SparepartTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SparepartTable extends PluginSparepartTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SparepartTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sparepart');
    }
}