<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/07/26 17:50:57

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=db_norad_vms',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
