<?php

/**
 * FleetOrder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FleetOrder extends PluginFleetOrder
{
	public function processDeparure()
	{
		$current_date = $date = date('Y/m/d H:i:s', time());
		$time = date('h:i:s A');
		$this->is_departed = true;
		$this->departure_date = $current_date;
		$this->departure_time = $time;
		$this->save();
	}
	
	public function processReturn()
	{
		
		$this->is_departed = false;
		$this->save();
	}
}
