<?php

/**
 * FleetServiceTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FleetServiceTaskTable extends PluginFleetServiceTaskTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object FleetServiceTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FleetServiceTask');
    }
}