<?php

/**
 * FleetServiceTask
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FleetServiceTask extends PluginFleetServiceTask
{
	public function processDeparture()
	{
		$current_date = $date = date('Y/m/d', time());
		$time = date('h:i:s A');
		
		$this->is_departed = true;
		$this->effective_date = $current_date;
		$this->status_id = TaskCore::$ONFIELD;
		$this->save();
		 
	}
	
	public function processReturn()
	{
		$this->is_returned = true;
		$this->save();
	}
	
	public function processComplete()
	{
		$current_date = $date = date('Y/m/d', time());
		
		$this->is_departed = true;
		$this->is_returned = true;
		$this->end_date = $current_date;
		$this->status_id = TaskCore::$COMPLETED;
		$this->save();
	}
	
	 
}
