<?php

/**
 * ServiceVehicleItemAcquiredTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiceVehicleItemAcquiredTable extends PluginServiceVehicleItemAcquiredTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServiceVehicleItemAcquiredTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServiceVehicleItemAcquired');
    }
}