<?php

/**
 * ServiceVehicleAccidentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiceVehicleAccidentTable extends PluginServiceVehicleAccidentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServiceVehicleAccidentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServiceVehicleAccident');
    }
}