<?php

/**
 * ServiceVehicleItemAcqAssignmentOrderuiredTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiceVehicleItemAcqAssignmentOrderuiredTable extends PluginServiceVehicleItemAcqAssignmentOrderuiredTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServiceVehicleItemAcqAssignmentOrderuiredTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServiceVehicleItemAcqAssignmentOrderuired');
    }
}