<?php

/**
 * ServiceAccidentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiceAccidentTable extends PluginServiceAccidentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServiceAccidentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServiceAccident');
    }
}