<?php

/**
 * ServiceTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiceTypeTable extends PluginServiceTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServiceTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServiceType');
    }
}