<?php

/**
 * PluginReturnTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginReturnTaskTable extends TaskTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginReturnTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginReturnTask');
    }
}