<?php

/**
 * PluginItemAcquiredAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginItemAcquiredAttachmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginItemAcquiredAttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginItemAcquiredAttachment');
    }
}