<?php

/**
 * PluginTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTaskTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTask');
    }
}