<?php

/**
 * PluginTimeMetricTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTimeMetricTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTimeMetricTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTimeMetric');
    }
}