<?php

/**
 * PluginTimeMetricConversionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTimeMetricConversionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTimeMetricConversionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTimeMetricConversion');
    }
}