<?php

/**
 * PluginCurrencyExchangeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCurrencyExchangeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCurrencyExchangeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCurrencyExchange');
    }
}