<?php

/**
 * PluginUnitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUnitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUnitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUnit');
    }
}