<?php

/**
 * PluginCurrencyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCurrencyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCurrencyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCurrency');
    }
}