<?php

/**
 * PluginCertificateTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCertificateTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCertificateTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCertificateType');
    }
}