<?php

/**
 * MaintenanceTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MaintenanceTaskTable extends PluginMaintenanceTaskTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MaintenanceTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MaintenanceTask');
    }
}