<?php

/**
 * CampusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CampusTable extends PluginCampusTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CampusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Campus');
    }
}