<?php

/**
 * CenterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CenterTable extends PluginCenterTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CenterTable
     */

    
    public static function selectCandidateParents()
    {}
    
   public static function addCenter ( $parent_id, $leader_id, $name, $director_name, $status, $project_no, $vat_number, $description, $street_no, $house_no, $pobox_no, $mobile_no, $phone_no, $fax_no, $email, $website)
	{
		$token = trim($name).trim($project_no).rand('11111', '99999');
		$_nw = new Center(); //
		$_nw->token_id = MD5($token);
		$_nw->participant_type_id = ParticipantTable::$INSTITUTION;
		$_nw->leader_participant_id = $leader_id;
		$_nw->name = trim($name); 
		$_nw->director_name = trim($director_name); 
		$_nw->status_id = $status; 
		$_nw->project_no = trim($project_no);
		$_nw->vat_number = trim($vat_number);
		$_nw->description = trim($description);
		$_nw->parent_id= $parent_id;
		$_nw->save(); 
		$_nw_id = $_nw->id;
		
			$contact = ParticipantContactTable::addContact($_nw_id, $street_no, $house_no, $pobox_no, $mobile_no, $phone_no, $fax_no, $email, $website);
		return true; 
	}

	public static function updateCenter($_id, $token_id, $parent_id, $leader_id, $name, $director_name, $status, $project_no, $vat_number, $description, $street_no, $house_no, $pobox_no, $mobile_no, $phone_no, $fax_no, $email, $website)
	{
		$q = Doctrine_Query::create( )
			->update('Center prt')
			->set('prt.participant_type_id', '?', ParticipantTable::$CENTER )
			->set('prt.name', '?', trim($name))
			->set('prt.leader_participant_id', '?',  $leader_id )
			->set('prt.director_name', '?', trim($director_name)) 
			->set('prt.status_id', '?', trim($status)) 
			->set('prt.project_no', '?', trim($project_no)) 
			->set('prt.vat_number', '?', trim($vat_number)) 
			->set('prt.description', '?', trim($description)) 
			->set('prt.parent_id', '?', $parent_id ) 
			->where('prt.id = ? AND prt.token_id = ?', array($_id, $token_id))
			->execute();	
			
			$contact = ParticipantContactTable::updateContact($_id, $street_no, $house_no, $pobox_no, $mobile_no, $phone_no, $fax_no, $email, $website);
			
		return ( $q > 0 );   
	}
   
  public static function processObject($_id, $token_id)
	{
		$q = Doctrine_Query::create()
			->select("prt.*, prt.name as firstName, pt.father_name as fatherName, pt.grand_father_name as grandFatherName, pt.full_name as fullName, prt.leader_participant_id as leaderID, prt.project_no as projectNo, prt.vat_number as vatNo, prt.status_id as partyStatus, prt.campus_id, campusID, prt.alias as partyAlias, prt.parent_id as parentID, prt.token_id as tokenID, prt.participant_type as typeID, prtcnt.mobile_number as mobileNo, prtcnt.phone_number as phoneNo, prtcnt.pobox as pobox, prtcnt.email as email, prtcnt.website as website, cmps.name as campusName")
				->from("Center prt") 
				->leftJoin("prt.Participant pt") 
				->leftJoin("prt.participantContacts prtcnt")
				->leftJoin("prt.Campus cmps")
				->where("prt.id = ? AND prt.token_id = ? AND prt.participant_type = ?", array($_id, $token_id, ParticipantCore::$CENTER) )
			->fetchOne(); 
		return (! $q ? null : $q ); 	
		
	}
	
	public static function processSelection($status=null, $keyword=null, $exclusion=null, $type=null, $offset=0, $limit=10 ) 
	{
		$q = Doctrine_Query::create()
				->select("prt.*, prt.name as firstName, pt.father_name as fatherName, pt.grand_father_name as grandFatherName, pt.full_name as fullName, prt.leader_participant_id as leaderID, prt.project_no as projectNo, prt.vat_number as vatNo, prt.status_id as partyStatus, prt.campus_id, campusID, prt.alias as partyAlias, prt.parent_id as parentID, prt.token_id as tokenID, prt.participant_type as typeID, prtcnt.mobile_number as mobileNo, prtcnt.phone_number as phoneNo, prtcnt.pobox as pobox, prtcnt.email as email, prtcnt.website as website, cmps.name as campusName")
				->from("Center prt") 
				->leftJoin("prt.Participant pt") 
				->leftJoin("prt.participantContacts prtcnt")
				->leftJoin("prt.Campus cmps")
				->offset($offset)
				->limit($limit)
				->where("prt.participant_type = ?", ParticipantCore::$CENTER);
				if(! is_null($status))
					$q = $q->andWhere("prt.status_id=?", $status);
				if(! is_null($type))
					$q = $q->andWhere("prt.participant_type=?", $type);
				if(!is_null($keyword) )
					$q = $q->andWhere("prt.name LIKE ? AND prt.project_no LIKE ?", array( $keyword, $keyword));
					
				$q = $q->execute( ); 

		return ( count ( $q ) <= 0 ? null : $q ); 
	}
    
	public static function processUmbrellaSelection($status=null, $keyword=null, $exclusion=null, $type=null, $offset=0, $limit=10 )
	{
		$q = Doctrine_Query::create()
				->select("prt.*, prt.name as firstName, pt.father_name as fatherName, pt.grand_father_name as grandFatherName, pt.full_name as fullName, prt.leader_id as leaderID, prt.project_no as projectNo, prt.vat_number as vatNo, prt.status_id as partyStatus, prt.campus_id, campusID, prt.alias as partyAlias, prt.parent_id as parentID, prt.token_id as tokenID, prt.participant_type as typeID, prtcnt.mobile_number as mobileNo, prtcnt.phone_number as phoneNo, prtcnt.pobox as pobox, prtcnt.email as email, prtcnt.website as website, cmps.name as campusName")
				->from("Participant prt") 
				->leftJoin("prt.Participant pt") 
				->leftJoin("prt.participantContacts prtcnt")
				->leftJoin("prt.Campus cmps")
				->offset($offset)
				->limit($limit)
				->where("prt.participant_type = ? ", ParticipantCore::$OFFICE);
				if(! is_null($status))
					$q = $q->andWhere("prt.status_id=?", $status);
				if(! is_null($type))
					$q = $q->andWhere("prt.participant_type=?", $type);
				if(!is_null($keyword) )
					$q = $q->andWhere("prt.name LIKE ? AND prt.project_no LIKE ?", array( $keyword, $keyword));
					
				$q = $q->execute( ); 

		return ( count ( $q ) <= 0 ? null : $q ); 
	}
    
	public static function processStatusSelection ()
	{
		$q = Doctrine_Query::create()
			->select("DISTINCT(prt.status_id) AS partyStatus")
			->from("Center prt") 
			->where("prt.status_id IS NOT NULL")		
			->execute();
		
		$status = array();
		foreach( $q as $w)
			$status[] = $w->partyStatus;
	 
		return ( count ( $status ) <= 0 ? null : $status );
	}

	public static function processTypeSelection()
	{
		$q = Doctrine_Query::create()
			->select("DISTINCT(prt.participant_type) AS partyType")
			->from("Center prt") 
			->where("prt.participant_type IS NOT NULL")		
			->execute();
		
		$types = array();
		foreach( $q as $w)
			$types[] = $w->partyType;
	 
		return ( count ( $types ) <= 0 ? null : $types );
	}

	
	public static function getInstance()
	{
		return Doctrine_Core::getTable('Center');
	}
}
