<?php

/**
 * CollegeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CollegeTable extends PluginCollegeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CollegeTable
     */
    public static function selectCollegeObject()
    {}
    
    public static function selectCollege()
    {}
    
    public static function selectCandidateParents()
    {}
    
    public static function addCollege()
    {}
    
    public static function updateCollege()
    {}
    
    public static function deleteCollege()
    {}
    
    public static function addKeywordQuery()
    {}
    
    public static function addStatusQuery()
    {}
    
    public static function addExclusionQuery()
    {}
    
    public static function addUmbrellaQuery()
    {}
    
    public static function selectStatusList()
    {}
    
    public static function selectTypeList()
    {}
    public static function getInstance()
    {
        return Doctrine_Core::getTable('College');
    }
}
