<?php

/**
 * CompanyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompanyTable extends PluginCompanyTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompanyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Company');
    }
	
    public static function processCreate ( $parent_id, $leader_id, $name, $director_name, $status, $project_no, $vat_number, $description, $street_no, $house_no, $pobox_no, $mobile_no, $phone_no, $fax_no, $email, $website)
	{
		$token = trim($name).trim($project_no).rand('11111', '99999');
		$_nw = new Center(); //
		$_nw->token_id = MD5($token);
		$_nw->participant_type_id = ParticipantTable::$INSTITUTION;
		$_nw->leader_participant_id = $leader_id;
		$_nw->name = trim($name); 
		$_nw->director_name = trim($director_name); 
		$_nw->status_id = $status; 
		$_nw->project_no = trim($project_no);
		$_nw->vat_number = trim($vat_number);
		$_nw->description = trim($description);
		$_nw->parent_id= $parent_id;
		$_nw->save(); 
		$_nw_id = $_nw->id;
		
			$contact = ParticipantContactTable::processCreate ($_nw_id, $street_no, $house_no, $pobox_no, $mobile_no, $phone_no, $fax_no, $email, $website);
			
		return true; 
	}

	public static function processUpdate ($_id, $token_id, $parent_id, $leader_id, $name, $dean_name, $status, $project_no, $vat_number, $description, $street_no, $house_no, $pobox_no, $mobile_no, $phone_no, $fax_no, $email, $website)
	{
		$q = Doctrine_Query::create( )
			->update('Center prt')
			->set('prt.participant_type_id', '?', ParticipantTable::$CENTER )
			->set('prt.name', '?', trim($name))
			->set('prt.leader_participant_id', '?',  $leader_id )
			->set('prt.dean_name', '?', trim($dean_name)) 
			->set('prt.status_id', '?', trim($status)) 
			->set('prt.project_no', '?', trim($project_no)) 
			->set('prt.vat_number', '?', trim($vat_number)) 
			->set('prt.description', '?', trim($description)) 
			->set('prt.parent_id', '?', $parent_id ) 
			->where('prt.id = ? AND prt.token_id = ?', array($_id, $token_id))
			->execute();	
			
			$contact = ParticipantContactTable::processUpdate ($_id, $street_no, $house_no, $pobox_no, $mobile_no, $phone_no, $fax_no, $email, $website);
			
		return ( $q > 0 );   
	}
	
	public static function processDelete($_id, $token_id)
	{
		
		
	} 
	 
	 public static function processObject($_id, $token_id)
	{
		$q= Doctrine_Query::create()
			->select("prt.* ")
			->from("Participant prt") // 
			->where("prt.id = ? AND prt.token_id = ?",array($_id, $token_id) )
			->fetchOne(); 
		return (! $q ? null : $q ); 	
		
	}
	
	public static function processSelection($status=null, $keyword=null, $exclusion=null , $parent=null, $dept=null, $type=null, $offset=0, $limit=10 ) 
	{
		$q= Doctrine_Query::create()
			->select("prt.*, prt.name as firstName, prt.father_name as fatherName, prt.grand_father_name as grandFatherName, prt.full_name as fullName")
			->from("Participant prt") 
			//->leftJoin("prt.Participant dept on dept.id = prt.dept_id")
			->offset($offset)
			->limit($limit)
			->where("prt.parent_id IS NOT NULL AND prt.participant_type = ?", ParticipantCore::$EMPLOYEE ); 
		$q= self::addStatusQuery($q, $status );
		$q= self::addKeywordQuery($q, $keyword );
		$q= self::addExclusionQuery($q, $exclusion );
		//$q= self::addUmbrellaQuery($q, $parent );
		if(! is_null($dept))
			$q=$q->andWhere("dept.id=?", $dept);
		$q= $q->execute( ); 

		return ( count ( $q ) <= 0 ? null : $q ); 
	}
}
