<?php

/**
 * Employee
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Employee extends PluginEmployee
{
	
	public function getFullName()
	{
		return $this->name.' '.$this->father_name .' '.$this->grand_father_name;
	}
	
	public function changeEmploymentType($employment_type)
	{
		$this->setEmploymentType($employment_type);
		$this->save();		
	}
}
