<?php

/**
 * OfficeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OfficeTable extends PluginOfficeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OfficeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Office');
    }
}