<?php

/**
 * ParticipantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParticipantTable extends PluginParticipantTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParticipantTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Participant');
    }
}