<?php

/**
 * ParticipantTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParticipantTypeTable extends PluginParticipantTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParticipantTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ParticipantType');
    }
}