<?php

/**
 * ParticipantContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParticipantContactTable extends PluginParticipantContactTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParticipantContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ParticipantContact');
    }
}