<?php

/**
 * BaseVehicleChakupSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $service_period
 * @property integer $period_frequency
 * @property Doctrine_Collection $vehicleTypes
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVehicleChakupSetting extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vehicle_chakup_setting');
        $this->hasColumn('service_period', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('period_frequency', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Vehicle as vehicleTypes', array(
             'local' => 'id',
             'foreign' => 'checkup_period_id'));
    }
}