<?php

/**
 * BaseVehicleInsuranceSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $vehicle_id
 * @property string $insurer_name
 * @property string $insurance_number
 * @property integer $insurance_type
 * @property integer $insurance_period
 * @property string $insurance_expiry_date
 * @property string $last_insurance_renewal
 * @property boolean $insurance_status
 * @property Vehicle $Vehicle
 * 
 * @package    noradVMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVehicleInsuranceSetting extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vehicle_insurance_setting');
        $this->hasColumn('vehicle_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('insurer_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('insurance_number', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('insurance_type', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('insurance_period', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('insurance_expiry_date', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('last_insurance_renewal', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('insurance_status', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Vehicle', array(
             'local' => 'vehicle_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}